import io
import pandas as pd
import matplotlib.pyplot as plt
import streamlit as st
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, KeepTogether, PageBreak
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

def generate_pdf_report(excel_file):
    pdf_buffer = io.BytesIO()
    
    # Set default portrait printable width (A4: 595.27 x 841.89 points)
    # Using Landscape orientation for readable multi-column data
    doc = SimpleDocTemplate(
        pdf_buffer,
        pagesize=landscape(A4),
        rightMargin=20,
        leftMargin=20,
        topMargin=25,
        bottomMargin=25
    )
    story = []
    
    printable_width = landscape(A4)[0] - 40  # ~801 points

    # Typography Styles
    title_style = ParagraphStyle(
        'DocTitle',
        fontName='Helvetica-Bold',
        fontSize=16,
        textColor=colors.HexColor('#1E293B'),
        spaceAfter=2
    )
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        fontName='Helvetica',
        fontSize=9,
        textColor=colors.HexColor('#64748B'),
        spaceAfter=10
    )
    section_style = ParagraphStyle(
        'SectionHeader',
        fontName='Helvetica-Bold',
        fontSize=11,
        textColor=colors.HexColor('#0F172A'),
        spaceBefore=10,
        spaceAfter=6
    )
    tbl_header_style = ParagraphStyle(
        'TableHeader',
        fontName='Helvetica-Bold',
        fontSize=6.5,
        leading=8,
        textColor=colors.whitesmoke,
        alignment=1
    )
    tbl_cell_style = ParagraphStyle(
        'TableCell',
        fontName='Helvetica',
        fontSize=6,
        leading=7.5,
        textColor=colors.HexColor('#334155'),
        alignment=0
    )

    def make_dynamic_table(df):
        """Creates an auto-fitted, clean ReportLab table wrapped in landscape mode."""
        df_clean = df.copy()
        df_clean.columns = [str(c).strip() for c in df_clean.columns]
        
        # Remove empty columns generated by Excel imports (e.g., 'Unnamed: X')
        df_clean = df_clean.loc[:, ~df_clean.columns.str.contains('^Unnamed')]
        
        num_cols = len(df_clean.columns)
        if num_cols == 0:
            return None

        # Dynamically scale column widths to fit page width
        col_width = printable_width / num_cols
        col_widths = [col_width] * num_cols

        data = [[Paragraph(str(col), tbl_header_style) for col in df_clean.columns]]
        
        for _, row in df_clean.iterrows():
            row_data = []
            for cell in row:
                if pd.isna(cell):
                    cell_text = ""
                elif isinstance(cell, (int, float)):
                    cell_text = f"{cell:,.2f}".rstrip('0').rstrip('.') if isinstance(cell, float) else f"{cell:,}"
                else:
                    cell_text = str(cell).strip()
                row_data.append(Paragraph(cell_text, tbl_cell_style))
            data.append(row_data)

        t = Table(data, colWidths=col_widths, repeatRows=1)
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1E3A8A')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
            ('LEFTPADDING', (0, 0), (-1, -1), 2),
            ('RIGHTPADDING', (0, 0), (-1, -1), 2),
            ('GRID', (0, 0), (-1, -1), 0.4, colors.HexColor('#CBD5E1')),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F8FAFC')])
        ]))
        return t

    def create_sheet_chart(df, sheet_name):
        """Generates clear bar charts filtered for valid numerical data."""
        df_plot = df.copy()
        df_plot.columns = [str(c).strip() for c in df_plot.columns]
        df_plot = df_plot.loc[:, ~df_plot.columns.str.contains('^Unnamed')]

        cat_cols = [c for c in df_plot.columns if any(k in c.lower() for k in ['date', 'name', 'person', 'party', 'item', 'kpi', 'description', 'po'])]
        num_cols = [c for c in df_plot.columns if any(k in c.lower() for k in ['val', 'amount', 'price', 'value', 'qty', 'total', 'order'])]

        cat_col = cat_cols[0] if cat_cols else df_plot.columns[0]
        num_col = num_cols[0] if num_cols else None

        if not num_col:
            return None

        df_plot[num_col] = pd.to_numeric(df_plot[num_col], errors='coerce').fillna(0)
        df_plot[cat_col] = df_plot[cat_col].astype(str).str.strip()

        df_plot = df_plot[df_plot[num_col] > 0]
        if df_plot.empty:
            return None

        grouped = df_plot.groupby(cat_col, as_index=False)[num_col].sum().head(12)  # Limit top 12 items for readability

        fig, ax = plt.subplots(figsize=(8.5, 2.2), dpi=150)
        bars = ax.bar(grouped[cat_col], grouped[num_col], color='#2563EB', edgecolor='#1D4ED8', width=0.4)

        ax.set_title(f"{num_col} by {cat_col} ({sheet_name.strip()})", fontsize=8, fontweight='bold', pad=8)
        ax.ticklabel_format(style='plain', axis='y')

        max_val = grouped[num_col].max()
        if max_val >= 1e5:
            ax.get_yaxis().set_major_formatter(plt.FuncFormatter(lambda x, loc: f"{x/1e5:,.1f} L"))

        plt.xticks(rotation=15, ha='right', fontsize=6.5)
        plt.yticks(fontsize=6.5)
        plt.grid(axis='y', linestyle='--', alpha=0.5)
        plt.tight_layout()

        img_buf = io.BytesIO()
        plt.savefig(img_buf, format='png', bbox_inches='tight')
        plt.close(fig)
        img_buf.seek(0)
        return Image(img_buf, width=8.5*inch, height=2.2*inch)

    xls = pd.ExcelFile(excel_file)

    # Document Header
    story.append(Paragraph("IRONMART MANAGEMENT AUDIT REPORT", title_style))
    story.append(Paragraph("Automated Multi-Sheet Consolidated Review", subtitle_style))

    # Iterate Over Sheets
    for idx, sheet_name in enumerate(xls.sheet_names, start=1):
        df_sheet = pd.read_excel(xls, sheet_name)
        
        # Drop completely empty rows and columns
        df_sheet = df_sheet.dropna(how='all').dropna(how='all', axis=1)
        if df_sheet.empty:
            continue

        clean_section_title = f"{idx}. {sheet_name.strip().title()} Summary"
        
        sheet_elements = [Paragraph(clean_section_title, section_style)]
        
        table = make_dynamic_table(df_sheet)
        if table:
            sheet_elements.append(table)
            sheet_elements.append(Spacer(1, 8))

        chart_img = create_sheet_chart(df_sheet, sheet_name)
        if chart_img:
            sheet_elements.append(chart_img)
            sheet_elements.append(Spacer(1, 10))

        # Add section elements with forced page breaks between main modules
        story.append(KeepTogether(sheet_elements))
        if idx < len(xls.sheet_names):
            story.append(PageBreak())

    doc.build(story)
    pdf_buffer.seek(0)
    return pdf_buffer

# Streamlit Interface
st.title("Excel to PDF Audit Report Generator")
uploaded_file = st.file_uploader("Upload Excel File (.xlsx)", type=["xlsx"])

if uploaded_file is not None:
    if st.button("Generate PDF Report"):
        with st.spinner("Processing all sheets into optimized PDF..."):
            pdf_data = generate_pdf_report(uploaded_file)
            st.success("Report generated successfully!")
            st.download_button(
                label="Download PDF Report",
                data=pdf_data,
                file_name="Audit_Report_Output_Fixed.pdf",
                mime="application/pdf"
            )
